version: '3.5'
services:
  influxdb:
    restart: always
    image: tutum/influxdb:latest
    ports:
      - "8083:8083"
      - "8086:8086"
    deploy:
     replicas: 1
     restart_policy:
      condition: on-failure
     resources:
        limits:
          cpus: '0.1'
          memory: "256M"
    environment:
      - ADMIN_USER="root" 
      - INFLUXDB_INIT_PWD="influxdb" 
      - PRE_CREATE_DB="AppMetrics;"
      - SERVICE_NAME=influxdb
      - SERVICE_TAGS=apm
    #volumes:
    #  - /media/sdb1/influxdb:/data

  